spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: "rainick98"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always


logging.level:
  org.hibernate.SQL: debug
#  org.springframework: debug
#  org.springframework.web: debug

server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true