spring:
  datasource:
    url: "jdbc:h2:mem://localhost/~/shop"
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console


logging.level:
  org.hibernate.SQL: debug
#  org.springframework: debug
#  org.springframework.web: debug

server:
  servlet:
    encoding:
      force: true